# Generated by Django 3.1.7 on 2021-02-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_tables', '0002_inputdata_bpm_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
