# Generated by Django 3.1.7 on 2021-02-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_tables', '0003_auto_20210226_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='insert_complete',
            field=models.CharField(default='OK', max_length=10),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='type_of_test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
