# Generated by Django 3.1.7 on 2021-02-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_tables', '0005_remove_inputdata_insert_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='insert_complete',
            field=models.CharField(default='', max_length=10),
        ),
    ]
