# Generated by Django 3.1.7 on 2021-02-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_tables', '0007_remove_inputdata_insert_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undertaketeam',
            name='country_cn',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='undertaketeam',
            name='undertake_team',
            field=models.CharField(max_length=200),
        ),
    ]
