# Generated by Django 3.1.7 on 2021-02-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_tables', '0008_auto_20210227_1540'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='undertaketeam',
            unique_together=set(),
        ),
    ]
