# Generated by Django 3.1.7 on 2021-02-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_tables', '0009_auto_20210227_1556'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='undertaketeam',
            unique_together={('country_cn', 'undertake_team', 'undertake_date')},
        ),
    ]
